### ISSUE TITLE
Team Members

### ISSUE THREAD

**Issue by anas599** [anas599/Recipe-app#18]
Hello dear Reviewer we are a team of 2 members for the Recipe app project

- @anas599 
- @Uthmanbello 

below is the link to the project kanban board
[Recipe-app](https://github.com/anas599/Recipe-app/projects/1)

Thanks

**Comment by codecaiine** [comment]
Hi @anas599 @Uthmanbello , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has the wrong info 😢 . You add the link to your repo instead of your GITHUB PROJECT . Please fix it 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by cynthiainga** [comment]
Hi @anas599 & @Uthmanbello, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] Descriptive issue ✔️ 
- [ ] All cards are assigned ✔️ 
- [ ] All cars have a descriptive title, number of points in the [Xpt] prefix, and a description of the task ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
